title: Aubrin Antwine
logo: assets/img/IMG_6725.JPG
description: Student studying public affairs and economics at the University of Texas at Austin, interested in how data drives policy and economic decisions, particularly in education.
show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
