title: Aubrin Antwine
logo: assets/img/IMG_6725.JPG
description: Student studying public affairs and economics at the University of Texas at Austin, interested in how data drives policy and economic decisions.
email: ada3654@eid.utexas.edu
links:
  https://www.linkedin.com/in/aubrinantwine/
  https://github.com/aubrinantwine
remote_theme: pages-themes/minimal@v0.2.0
show_downloads: false
color-scheme: auto
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error —
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]
